global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'streammetrics-producer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']

  - job_name: 'streammetrics-consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8084']